### PR TITLE
docs: replace dead link to selenium webdriver

### PR DESCRIPTION
**Pull request by drc-nloftsgard**
docs have moved to https://www.selenium.dev/documentation/en/

### CODE REVIEW

**Comment by drc-nloftsgard** [comment]
Also it seems that creating/building the driver has changed and should be

```
var driver = await new Builder()
    .forBrowser('firefox')
    .build();
```

**Review by straker — APPROVED** [review]

**Comment by straker** [comment]
Thanks for the doc update, I really like the new docs. As for the example, it should still be fine as you'd have to decronstruct the `WebDriver` object to get `Builder` on it's own, so the example should still work as it is written.

**Comment by straker** [comment]
Seems circle never got the message about a new pr... Could you push an empty commit to retrigger the build? `git commit -m "trigger build" --allow-empty`

**Comment by WilcoFiers** [comment]
@drc-nloftsgard Thank you for the contribution!

**Pull request merged**
