### PR TITLE
Build: selenium-webdriver should be a peer dependency

### LINKED ISSUE #1: axe-webdriverjs should have peerDependency on selenium-webdriver
This package requires selenium -webdriver to be present but does not depend on it because it assumes it is present already in projects. This makes it a peer dependency.

http://blog.nodejs.org/2013/02/07/peer-dependencies/

### PR DESCRIPTION
**Pull request by arschmitz**
For once you start accepting pull requests

Fixes #1
Closes #2

### CODE REVIEW

**Comment by dsturley** [comment]
Please sign the [CLA](https://cla-assistant.io/dequelabs/axe-webdriverjs) and I can accept this pull request.

**Comment by arschmitz** [comment]
@dsturley done!

**Comment by dylanb** [comment]
Hey @arschmitz nice to see you contributing to aXe related projects!!

**Comment by arschmitz** [comment]
@dylanb would there be interest in adding jscs to this and axe-core to automate enforcement of your style guide? If there is id be happy to do it?

**Comment by dylanb** [comment]
We currently state that we will only loosely enforce the style guide in the contribution guidelines... @dsturley WDYT?

**Comment by dylanb** [comment]
@arschmitz the repo has now been made public and you can contribute if you like https://github.com/dequelabs/axe-grunt-webdriver

**Pull request merged**
